version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: homedine-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build: ./backend
    container_name: homedine-backend
    env_file:
      - ./backend/.env.docker
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: homedine-frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "80:80"

volumes:
  mongodata:
